### ISSUE TITLE
exe 빌드업 후 실행 오류

### ISSUE THREAD

**Issue by Haritage** [Queue-ri/Korea-Covid-19-Vaccine-Reservation#4]
Last login: Thu Aug  5 13:36:26 on ttys002
/Users/mac/Downloads/Korea-Covid-19-Vaccine-Reservation-1.3/cb ; exit;

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
(base) gimsanghyeog-ui-MacBook-Pro:~ mac$ /Users/mac/Downloads/Korea-Covid-19-Vaccine-Reservation-1.3/cb ; exit;
Traceback (most recent call last):
  File "cb.py", line 3, in <module>
ModuleNotFoundError: No module named 'browser_cookie3'
[12046] Failed to execute script 'cb' due to unhandled exception!
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[프로세스 완료됨]

이러한 오류가 발생하네요 ㅠ

**Comment by Queue-ri** [comment]
dependency 문제로, 프로그램 버그가 아닙니다.

`requirements.txt` 를 사용해주세요.

**Comment by ejrwoals** [comment]
requirements.txt 다 설치하고 exe 빌드하고 크롬창 열고 실행했는데 

Traceback (most recent call last):
  File "cb.py", line 20, in <module>
  File "browser_cookie3|__init__.py", line 596, in chrome
  File "browser_cookie3|__init__.py", line 383, in __init__
  File "browser_cookie3|__init__.py", line 192, in __init__
  File "browser_cookie3|__init__.py", line 249, in __add_key-and_cookie_file
browser_cookie3.BrowserCookieError: Failed to find Chrome cookie
[9612] Failed to execute script 'cb' due to unhandled exception!

이렇게 뜨고 콘솔창이 바로 꺼지네요.. 왜 그런걸까요ㅜ

**Comment by Queue-ri** [comment]
@ejrwoals 쿠키 문제입니다. `README.md` 참고해주세요.
